# References:
#  1. Private network: https://github.com/k8sp/auto-install/issues/102#issuecomment-238005425
#  2. Install Docker: https://docs.docker.com/engine/installation/linux/ubuntulinux/
Vagrant.configure("2") do |config|

  config.vm.define "bootstrapper" do |bs|
    bs.vm.box = "ubuntu/trusty64"

    bs.vm.synced_folder "~/work", "/work"

    bs.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "2048"
    end

    # Install Docker on both VMs.
    bs.vm.provision "shell", inline: <<-SHELL
apt-get update
apt-get install -y apt-transport-https ca-certificates
apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
touch /etc/apt/sources.list.d/docker.list
chown vagrant /etc/apt/sources.list.d/docker.list
echo 'deb https://apt.dockerproject.org/repo ubuntu-trusty main' >> /etc/apt/sources.list.d/docker.list
apt-get update
apt-get install -y linux-image-extra-$(uname -r)
apt-get install -y docker-engine
service docker start
groupadd docker
usermod -aG docker vagrant
echo '192.168.50.4 bootstrapper' >> /etc/hosts
  SHELL

    bs.vm.network "public_network", ip: "192.168.50.4", bridge: "en3"
    bs.vm.hostname = "bootstrapper"
  end

  config.vm.define "node" do |nd|
    nd.vm.box = "c33s/empty"
    nd.vm.network "public_network", type: "dhcp", bridge: "en3"

    nd.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.memory = "2048"
    end
  end
end
