master
========
        - name: "install-k8s.service"
          command: restart
          content: |
            [Unit]
            Description=Install k8s services

            [Service]
            ExecStart=cd /home/core && /usr/bin/wget -O master.zip http://10.10.10.192/install-k8s/master.zip && unzip -o master.zip && cd master && bash setup_k8s_master.sh
            RemainAfterExit=yes
            Type=oneshot


worker
=========
        - name: "install-k8s.service"
          command: restart
          content: |
            [Unit]
            Description=Install k8s services

            [Service]
            ExecStart=cd /home/core && /usr/bin/wget -O worker.zip http://10.10.10.192/install-k8s/worker.zip && unzip -o worker.zip && cd worker && bash setup_k8s_worker.sh
            RemainAfterExit=yes
            Type=oneshot
