---
- hosts: k8s-15 
  roles:
    - role: common
  tags: cluster

- hosts: master
  roles:
    - role: master 
  tags: master

- hosts: worker
  roles:
    - role: worker
  tags: worker

- hosts: k8s-15
  roles: 
    - role: centos
  tags: cluster 
