// cloud-config-server starts an HTTP server, which can be accessed
// via URLs in the form of
//
//   http://<addr:port>?mac=aa:bb:cc:dd:ee:ff
//
// and returns the cloud-config YAML file specificially tailored for
// the node whose primary NIC's MAC address matches that specified in
// above URL.
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"io/ioutil"
	"log"
	"net"
	"net/http"
	"os"
	"path"
	"strings"
	"text/template"

	"github.com/gorilla/mux"
	"github.com/k8sp/sextant/cloud-config-server/cache"
	"github.com/k8sp/sextant/cloud-config-server/certgen"
	cctemplate "github.com/k8sp/sextant/cloud-config-server/template"
	"github.com/k8sp/sextant/clusterdesc"
	"github.com/topicai/candy"
	"gopkg.in/yaml.v2"
)

func main() {
	clusterDescURL := flag.String("cluster-desc-url",
		"https://raw.githubusercontent.com/k8sp/sextant/master/cloud-config-server/template/cluster-desc.sample.yaml",
		"URL to remote cluster description YAML file.")
	clusterDescFile := flag.String("cluster-desc-file", "./cluster-desc.yml", "Local copy of cluster description YAML file.")

	ccTemplateURL := flag.String("cc-template-url",
		"https://raw.githubusercontent.com/k8sp/sextant/master/cloud-config-server/template/cloud-config.template",
		"URL to cloud-config file template.")
	ccTemplateFile := flag.String("cc-template-file", "./cloud-config.template", "Local copy of cloud-config file template.")

	caCrt := flag.String("ca-crt", "", "CA certificate file, in PEM format")
	caKey := flag.String("ca-key", "", "CA private key file, in PEM format")
	addr := flag.String("addr", ":8080", "Listening address")

	dir := flag.String("dir", "./static/", "The directory to serve files from. Default is ./static/")

	validate := flag.Bool("validate", false, "Validate cluster-desc.yaml and the generated cloud-config file.")

	flag.Parse()

	if len(*caCrt) == 0 || len(*caKey) == 0 {
		*caKey, *caCrt = certgen.GenerateRootCA("./")
	}
	// valid caKey and caCrt file is ready
	candy.Must(fileExist(*caCrt))
	candy.Must(fileExist(*caKey))

	c := makeCacheGetter(*clusterDescURL, *clusterDescFile)
	t := makeCacheGetter(*ccTemplateURL, *ccTemplateFile)

	// Validate cluster-desc.yaml, the generated cloud-config.yaml which generated by the mac in cluster-desc
	if *validate == true {
		fmt.Printf("Checking %s ...", *clusterDescFile)
		err := validation(c, t, *caKey, *caCrt, *dir)
		if err != nil {
			fmt.Print("Failed: \n" + err.Error())
			os.Exit(1)
		} else {
			fmt.Println("Successed!")
		}
		os.Exit(0)
	}

	l, e := net.Listen("tcp", *addr)
	candy.Must(e)
	run(c, t, l, *caKey, *caCrt, *dir)
}

// Validate cluster-desc.yaml and check the generated cloud-config file format.
func validation(clusterDesc func() []byte, ccTemplate func() []byte, caKey, caCrt, dir string) error {
	tmpl := template.Must(template.New("validation").Parse(string(ccTemplate())))
	c := &clusterdesc.Cluster{}
	// validate cluster-desc format
	err := yaml.Unmarshal(clusterDesc(), c)
	if err != nil {
		return errors.New("cluster-desc file formate failed: " + err.Error())
	}

	// flannel backend only support host-gw and udp for now
	if c.FlannelBackend != "host-gw" && c.FlannelBackend != "udp" {
		return errors.New("Flannl backend should be host-gw or udp.")
	}

	var ccTmpl bytes.Buffer
	var macList []string
	macList = append(macList, "00:00:00:00:00:00")
	for _, n := range c.Nodes {
		macList = append(macList, n.Mac())
	}
	for _, mac := range macList {
		err = cctemplate.Execute(tmpl, c, mac, caKey, caCrt, &ccTmpl)
		if err != nil {
			return errors.New("Generate cloud-config failed with mac: " + mac + "\n" + err.Error())
		}
		yml := make(map[interface{}]interface{})
		err = yaml.Unmarshal(ccTmpl.Bytes(), yml)
		if err != nil {
			return errors.New("Generate cloud-config format failed with mac: " + mac + "\n" + err.Error())
		}
		ccTmpl.Reset()
	}
	return nil
}

// By making the first two parameters closures, we get the flexibility
// to create closures reading from the cache for production serving,
// and from constant values for testing.  Please refer to func main()
// for the former case, and server_test.go for the latter case.
func run(clusterDesc func() []byte, ccTemplate func() []byte, ln net.Listener, caKey, caCrt, dir string) {
	router := mux.NewRouter().StrictSlash(true)
	router.HandleFunc("/cloud-config/{mac}",
		makeSafeHandler(func(w http.ResponseWriter, r *http.Request) {
			mac := strings.ToLower(mux.Vars(r)["mac"])
			tmpl := template.Must(template.New("template").Parse(string(ccTemplate())))
			c := &clusterdesc.Cluster{}
			candy.Must(yaml.Unmarshal(clusterDesc(), c))
			candy.Must(cctemplate.Execute(tmpl, c, mac, caKey, caCrt, w))
		}))
	router.PathPrefix("/static/").Handler(http.StripPrefix("/static/", http.FileServer(http.Dir(dir))))

	log.Printf("%v", http.Serve(ln, router))
}

func makeSafeHandler(h http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		defer func() {
			if err := recover(); err != nil {
				http.Error(w, fmt.Sprint(err), http.StatusInternalServerError)
			}
		}()
		h(w, r)
	}
}

func makeCacheGetter(url, fn string) func() []byte {
	if len(fn) == 0 {
		dir, e := ioutil.TempDir("", "")
		candy.Must(e)
		fn = path.Join(dir, "localfile")
	}
	c := cache.New(url, fn)
	return func() []byte { return c.Get() }
}

func fileExist(fn string) error {
	_, err := os.Stat(fn)
	if err != nil || os.IsNotExist(err) {
		return errors.New("file " + fn + " is not ready.")
	}
	return nil
}
